$(".nav-button").on("click",function(){$(this).toggleClass("close"),$(this).parent().toggleClass("dark"),$(".nav").toggleClass("visible")}),$(".nav li").on("click",function(){$(".nav").removeClass("visible"),$(".nav-button").removeClass("close"),$(".nav-button").parent().removeClass("dark")}),$(".close-button").on("click",function(){$(".darkOverlay").hide()}),$(".contact-trigger").on("click",function(a){a.preventDefault(),$(".darkOverlay").show()}),$(".anchor").on("click",function(a){a.preventDefault();var e;return e=$(this.hash),$("html,body").animate({scrollTop:e.offset().top},500)}),$.preloadImages=function(){for(var a=0;a<arguments.length;a++)$("<img />").attr("src",arguments[a])},$.preloadImages("images/daisy.jpg","images/elyssa-palasi-portrait.svg","images/geometry.png","images/symphony.jpg","images/white-shape.svg","images/yssa-monogram.svg","images/projects/10k-challenge-2.jpg","images/projects/10k-challenge-thumb.png","images/projects/10k-challenge.jpg","images/projects/brochure-inside.jpg","images/projects/brochure-outside.jpg","images/projects/eagle-star.jpg","images/projects/expressappwizard.jpg","images/projects/free-spirit-dining-thumb.png","images/projects/freespiritdining.jpg","images/projects/income-plans.jpg","images/projects/lighthouse-brand-logo.png","images/projects/moneywise.jpg","images/projects/olo-acupuncture-thumb.png"),/*
 * CSS3 Animate it
 * Copyright (c) 2014 Jack McCourt
 * https://github.com/kriegar/css3-animate-it
 * Version: 0.1.0
 *
 * I utilise the jQuery.appear plugin within this javascript file so here is a link to that too
 * https://github.com/morr/jquery.appear
 *
 * I also utilise the jQuery.doTimeout plugin for the data-sequence functionality so here is a link back to them.
 * http://benalman.com/projects/jquery-dotimeout-plugin/
 */
function(a){function e(){n=!1;for(var e=0;e<i.length;e++){var s=a(i[e]).filter(function(){return a(this).is(":appeared")});if(s.trigger("appear",[s]),t){var o=t.not(s);o.trigger("disappear",[o])}t=s}}var t,i=[],s=!1,n=!1,o={interval:250,force_process:!1},r=a(window);a.expr[":"].appeared=function(e){var t=a(e);if(!t.is(":visible"))return!1;var i=r.scrollLeft(),s=r.scrollTop(),n=t.offset(),o=n.left,d=n.top;return d+t.height()>=s&&d-(t.data("appear-top-offset")||0)<=s+r.height()&&o+t.width()>=i&&o-(t.data("appear-left-offset")||0)<=i+r.width()?!0:!1},a.fn.extend({appear:function(t){var r=a.extend({},o,t||{}),d=this.selector||this;if(!s){var l=function(){n||(n=!0,setTimeout(e,r.interval))};a(window).scroll(l).resize(l),s=!0}return r.force_process&&setTimeout(e,r.interval),i.push(d),a(d)}}),a.extend({force_appear:function(){return s?(e(),!0):!1}})}(jQuery),/*!
 * jQuery doTimeout: Like setTimeout, but better! - v1.0 - 3/3/2010
 * http://benalman.com/projects/jquery-dotimeout-plugin/
 *
 * Copyright (c) 2010 "Cowboy" Ben Alman
 * Dual licensed under the MIT and GPL licenses.
 * http://benalman.com/about/license/
 */
// Copyright (c) 2010 "Cowboy" Ben Alman,
function(a){"$:nomunge";function e(e){function i(){e?o.removeData(e):p&&delete t[p]}function n(){d.id=setTimeout(function(){d.fn()},u)}var o,r=this,d={},l=e?a.fn:a,c=arguments,g=4,p=c[1],u=c[2],f=c[3];if("string"!=typeof p&&(g--,p=e=0,u=c[1],f=c[2]),e?(o=r.eq(0),o.data(e,d=o.data(e)||{})):p&&(d=t[p]||(t[p]={})),d.id&&clearTimeout(d.id),delete d.id,f)d.fn=function(a){"string"==typeof f&&(f=l[f]),f.apply(r,s.call(c,g))!==!0||a?i():n()},n();else{if(d.fn)return void 0===u?i():d.fn(u===!1),!0;i()}}var t={},i="doTimeout",s=Array.prototype.slice;a[i]=function(){return e.apply(window,[0].concat(s.call(arguments)))},a.fn[i]=function(){var a=s.call(arguments),t=e.apply(this,[i+a[0]].concat(a));return"number"==typeof a[0]||"number"==typeof a[1]?this:t}}(jQuery),$(".animatedParent").appear(),$(".animatedClick").click(function(){var a=$(this).attr("data-target");if(void 0!=$(this).attr("data-sequence")){var e=$("."+a+":first").attr("data-id"),t=$("."+a+":last").attr("data-id"),i=e;$("."+a+"[data-id="+i+"]").hasClass("go")?($("."+a+"[data-id="+i+"]").addClass("goAway"),$("."+a+"[data-id="+i+"]").removeClass("go")):($("."+a+"[data-id="+i+"]").addClass("go"),$("."+a+"[data-id="+i+"]").removeClass("goAway")),i++,delay=Number($(this).attr("data-sequence")),$.doTimeout(delay,function(){return console.log(t),$("."+a+"[data-id="+i+"]").hasClass("go")?($("."+a+"[data-id="+i+"]").addClass("goAway"),$("."+a+"[data-id="+i+"]").removeClass("go")):($("."+a+"[data-id="+i+"]").addClass("go"),$("."+a+"[data-id="+i+"]").removeClass("goAway")),++i,t>=i?!0:void 0})}else $("."+a).hasClass("go")?($("."+a).addClass("goAway"),$("."+a).removeClass("go")):($("."+a).addClass("go"),$("."+a).removeClass("goAway"))}),$(document.body).on("appear",".animatedParent",function(){var a=$(this).find(".animated"),e=$(this);if(void 0!=e.attr("data-sequence")){var t=$(this).find(".animated:first").attr("data-id"),i=t,s=$(this).find(".animated:last").attr("data-id");$(e).find(".animated[data-id="+i+"]").addClass("go"),i++,delay=Number(e.attr("data-sequence")),$.doTimeout(delay,function(){return $(e).find(".animated[data-id="+i+"]").addClass("go"),++i,s>=i?!0:void 0})}else a.addClass("go")}),$(document.body).on("disappear",".animatedParent",function(){$(this).hasClass("animateOnce")||$(this).find(".animated").removeClass("go")}),$(window).load(function(){$.force_appear()});